In [ ]:
# Stacking Arrays (Array birleşimleri)

In [ ]:
import numpy as np
from numpy import *

In [ ]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[-1,-2],[-3,-4]])

In [ ]:
# veritical ==> dikey birleştirme 
#array([[1, 2],
#       [3, 4]])
#array([[-1, -2],
#       [-3, -4]])

In [ ]:
array3 = np.vstack((array1,array2))

In [ ]:
print(array3)

In [ ]:
# horizontal ==> yatay birleştirme
#array([[1, 2],[-1, -2],
#       [3, 4]],[-3, -4]]

In [ ]:
array4 = np.hstack((array1,array2))

In [ ]:
print(array4)