In [1]:
# NumPy - NumPy Array'i Oluşturmak (Creating Numpy Arrays)

In [2]:
import numpy as np
from numpy import *

In [3]:
array1 = np.array([1, 2, 3, 4, 5])

In [4]:
print(type(np.array([1, 2, 3, 4, 5])))

<class 'numpy.ndarray'>


In [5]:
print(np.zeros(10, dtype=int)) # o lardan bir array oluşturmak

[0 0 0 0 0 0 0 0 0 0]


In [6]:
print(np.random.randint(0, 10, size=10)) # 0 - 10 arasında 10 tane elemanlı random bir array oluşturma

[8 6 5 1 7 2 8 5 4 7]


In [7]:
print(np.random.normal(10, 4, (3, 4))) # Ortalaması 10 - Standart sapması 4 olan 3'e 4'lük bir array oluşturma

[[ 6.95306602  3.8206611  13.40006717  8.13627773]
 [ 6.54896448  1.47391332 10.98994847  8.03607897]
 [ 5.0445671  17.18483877  7.40215762  6.29763877]]
