In [ ]:
# Shape Manipulation

In [1]:
import numpy as np
from numpy import *

In [2]:

array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [3]:
print(array.ravel()) # Matrixi tek boyutlu - vektör hal,ne getirme

[1 2 3 4 5 6 7 8 9]


In [4]:
print(array.reshape(3,3)) # etki ettigi arrayı degiştirmez. Başka bir degişkene eşitlersen array başka degişken üzerinde değişmiş olur. 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
array2 = array.T
print(array2) # Matrixin transpozunu alma

# array2.resize((2,3)) ==> etki ettigi arrayi değiştirir

[[1 4 7]
 [2 5 8]
 [3 6 9]]
