In [ ]:
# NumPy Basics Operations

In [1]:
import numpy as np
from numpy import * 

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [3]:
print(a+b)

[5 7 9]


In [4]:
print(a-b)

[-3 -3 -3]


In [5]:
print(a**2)

[1 4 9]


In [6]:
print(np.sin(a)) # a nin sinusunu al

[0.84147098 0.90929743 0.14112001]


In [7]:
print(a < 2) # True False False

[ True False False]


In [8]:
aa = np.array([[1,2,3],
               [4,5,6]])

bb = np.array([[1,2,3],
               [4,5,6]])

In [9]:
print("a x b ==> " , a*b)

a x b ==>  [ 4 10 18]


In [10]:
# print(aa.dot(bb)) # Matrix çarpimlarda aa satır sayısı bb sutun sayısına eşit olmalı bu sebeple bu işlemde hata alırız

print("==> \n" , aa.dot(bb.T)) # bb.T ==> b matrixinin transpozesini alma demektir.

==> 
 [[14 32]
 [32 77]]


In [11]:
aaa = np.random.random((5,5)) # 5 e 5 lik 0 ile 1 arasinda sayi üretmek.

In [12]:
print("Random 5 e 5 ==> " , aaa)

Random 5 e 5 ==>  [[0.48544249 0.47629194 0.5902049  0.13185601 0.41405419]
 [0.68130142 0.38137134 0.15945962 0.09027724 0.8373818 ]
 [0.09663916 0.76264897 0.88217108 0.02059146 0.75928998]
 [0.52780143 0.5406085  0.45983112 0.57893783 0.30572613]
 [0.20038659 0.53906641 0.16953842 0.88938948 0.13901688]]


In [13]:
aaa.sum() # Aray içindeki tüm degerlerin toplami ==>

11.119284382259659

In [ ]:
print("Arayin içindeki tüm degerlerin toplami ==>" , aaa.sum() )

In [14]:
aaa.max() # Aray içindeki max degeri ==>

0.8893894774865215

In [15]:
print("Arayin içindeki max degeri ==>" , aaa.max())

Arayin içindeki max degeri ==> 0.8893894774865215


In [16]:
aaa.min() # Aray içindeki min deger ==>

0.02059145524776751

In [17]:
print("Arayin içindeki min deger ==>" , aaa.min())

Arayin içindeki min deger ==> 0.02059145524776751


In [18]:
aaa.sum(axis=0) # Sutunlara göre toplama. Sadece sutun olarak toplama islemi yapilir.

array([1.99157109, 2.69998716, 2.26120513, 1.71105201, 2.45546899])

In [19]:
print("Sutunlara göre toplama ==>" , aaa.sum(axis=0))

Sutunlara göre toplama ==> [1.99157109 2.69998716 2.26120513 1.71105201 2.45546899]


In [20]:
aaa.sum(axis=1) # Satirlar kendi aralarinda toplanir

array([2.09784953, 2.14979142, 2.52134064, 2.41290502, 1.93739777])

In [21]:
print("Satirlar kendi aralarinda toplanir ==>" , aaa.sum(axis=1) )

Satirlar kendi aralarinda toplanir ==> [2.09784953 2.14979142 2.52134064 2.41290502 1.93739777]


In [22]:
print("Matrixin karekoku ==>" , np.sqrt(aaa))

Matrixin karekoku ==> [[0.69673703 0.69013907 0.76824794 0.36311983 0.64347043]
 [0.82540985 0.6175527  0.39932395 0.30046171 0.91508568]
 [0.3108684  0.87329775 0.93923963 0.14349723 0.87137247]
 [0.72649944 0.73526084 0.67810849 0.76087964 0.55292507]
 [0.4476456  0.73421142 0.41175043 0.94307448 0.37284967]]


In [23]:
print("Matrixin karesi ==>" , np.square(aaa)) # a**2

Matrixin karesi ==> [[2.35654409e-01 2.26854012e-01 3.48341828e-01 1.73860071e-02
  1.71440873e-01]
 [4.64171625e-01 1.45444101e-01 2.54273695e-02 8.14997995e-03
  7.01208287e-01]
 [9.33912732e-03 5.81633448e-01 7.78225809e-01 4.24008029e-04
  5.76521275e-01]
 [2.78574352e-01 2.92257554e-01 2.11444657e-01 3.35169014e-01
  9.34684678e-02]
 [4.01547839e-02 2.90592589e-01 2.87432757e-02 7.91013643e-01
  1.93256929e-02]]


In [24]:
print("İki matrixin toplamini ifade eder ==> " , np.add(aaa , aaa))

İki matrixin toplamini ifade eder ==>  [[0.97088498 0.95258388 1.18040981 0.26371202 0.82810838]
 [1.36260284 0.76274269 0.31891923 0.18055448 1.67476361]
 [0.19327832 1.52529794 1.76434215 0.04118291 1.51857996]
 [1.05560287 1.08121701 0.91966224 1.15787566 0.61145226]
 [0.40077317 1.07813281 0.33907684 1.77877895 0.27803376]]
