In [1]:
# Yeniden Şekillendirme (Reshaping)

In [2]:
import numpy as np
from numpy import *

In [3]:
array_1 = np.random.randint(1, 15, size = 12) # 1 - 15 arasinda 12 elemandan oluşan bir array oluştur. 

In [4]:
array_2 = array_1.reshape(4, 3) # oluşturdugun bu arrayi ( reshape komutu ile ) 4 e 3 lük bir matrise dönüştür

In [5]:
# Çevirecegimizin matrisin eleman sayilari birbirleri ile uyumlu olmali. 12 elemandan oluşan bir arrayi 12 elemanli bir matrise çevirmek zorundayiz.

In [6]:
print("Array 1 ==> " , array_1)

Array 1 ==>  [ 9  6  3 11  6  3  7  3  7  8  8 10]


In [7]:
print("Array 2 ==> " , array_2)

Array 2 ==>  [[ 9  6  3]
 [11  6  3]
 [ 7  3  7]
 [ 8  8 10]]
