In [2]:
import numpy as np # Bu tanimlama ile artik numpy paketi program içerisinde np ismiyle temsil edilecektir.

from numpy import * # Bu tanimlama ile numpy paketi içerisindeki tüm komutlar doğrudan çağrilabilir.

In [4]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [5]:
print(array.shape) # 15 e 1 lik bir vektör (15,)

(15,)


In [6]:
a = array.reshape(3,5) # 3 satir ve 5 sutunden oluşan bir array haline getir.

print("shape =>", a.shape)

shape => (3, 5)


In [7]:
print("Dimension =>",a.ndim) # Kaç boyutlu olduğunu gösterir. 3 e 5 ==> 2 boyutlu

print("Data typr =>" , a.dtype.name) # Arrayin içindeki data typlerin isimleri nedir ??  => int32

print("Size => " , a.size) #Reshape den önceki boyutunu verir  ==> 15 (1 e 15 lik bir vektördü)

print("type => " ,type(a)) # => type =>  <class 'numpy.ndarray'> 

Dimension => 2
Data typr => int32
Size =>  15
type =>  <class 'numpy.ndarray'>


In [8]:
array1 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,8,7,5]]) # Reshape kullanmadan matrix oluşturma

In [9]:
matrix0 = np.zeros((3,4)) # 3 e 4 lük sıfırlardan oluşan matrix oluşturma

In [11]:
matrix0[0][0] = 5
print(matrix0)



[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
matrix1 = np.ones((3,4)) # 3 e 4 lük birlerden oluşan matrix oluşturma
print(matrix1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
matrix_ = np.empty((5,4)) # 3 e 4 lük boşlardan oluşan matrix oluşturma
print(matrix_)

[[ 0.          2.63157895  5.26315789  7.89473684]
 [10.52631579 13.15789474 15.78947368 18.42105263]
 [21.05263158 23.68421053 26.31578947 28.94736842]
 [31.57894737 34.21052632 36.84210526 39.47368421]
 [42.10526316 44.73684211 47.36842105 50.        ]]


In [14]:
b = np.arange(0 , 90 , 12) # 0 - 90 arasındaki sayıları 12 şer olarak yazdır. Son sayılar genelde dahil olmaz 
print("==> " , b)

==>  [ 0 12 24 36 48 60 72 84]


In [15]:
c = np.linspace(0 , 50 , 20) # 0 - 50 arasında araya 20 tane sayı yazdır. Son sayı dahil.
print("==> " , c)

==>  [ 0.          2.63157895  5.26315789  7.89473684 10.52631579 13.15789474
 15.78947368 18.42105263 21.05263158 23.68421053 26.31578947 28.94736842
 31.57894737 34.21052632 36.84210526 39.47368421 42.10526316 44.73684211
 47.36842105 50.        ]


In [16]:
array2 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,8,7,5]]) 

In [17]:
print("Bellek adresi ==> " , array2.data) # Dizinin bellek adresini verir.

Bellek adresi ==>  <memory at 0x000001A14133E400>


In [18]:
print("Eleman sayisi ==> " , array2.size) # Dizinin eleman sayısını verir.

Eleman sayisi ==>  12


In [19]:
print("Tek boyutlu hali ==> " , array2.ravel()) # Matrisi tek boyutlu diziye çevirir.
#print(array2.flat)  Matrisi tek boyutlu diziye çevirir.

Tek boyutlu hali ==>  [1 2 3 4 5 6 7 8 9 8 7 5]
